const ProductsData = [
  {
    id: "maszynka-do-przycinania",
    name: "Maszynka do przycinania",
    description: "Opis produktu",
    image: "product1.jpg",
    details: "LOrem ipsum solor sit amet",
    price: 824.2302,
  },
  {
    id: "maszynka-do-przycinania2",
    name: "Pasta",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 2324.00,
  },
  {
    id: "maszynka-do-przycinania3",
    name: "Klej",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 354.30,
  },
  {
    id: "maszynka-do-przycinania4",
    name: "roman admin",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 354.00,
  },
  {
    id: "maszynka-do-przycinania5",
    name: "andrzej",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania6",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.02,
  },
  {
    id: "maszynka-do-przycinania7",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania8",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
];

export default ProductsData;
