const ProductsData = [
  {
    id: "maszynka-do-przycinania",
    name: "Maszynka do przycinania",
    description: "Opis produktu",
    image: "product1.jpg",
    details: "LOrem ipsum solor sit amet",
    price: 345.235667535,
  },
  {
    id: "maszynka-do-przycinania2",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania3",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania4",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania5",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania6",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.02,
  },
  {
    id: "maszynka-do-przycinania7",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
  {
    id: "maszynka-do-przycinania8",
    name: "Maszynka do przycinania",
    description: "Maszynka do przycinania",
    image: "product2.jpg",
    details: "Test2",
    price: 345.00,
  },
];

export default ProductsData;
